### ISSUE TITLE
Solang: Support ETH ABI encoding

### ISSUE THREAD

**Issue by xermicus** [paritytech/roadmap#16]
The `contracts` pallet will [introduce ETH RPC methods](https://github.com/paritytech/polkadot-sdk/issues/111). Since the call data will be encoded using the ETH ABI encoding scheme, contracts need to understand ETH ABI encoding and decoding. This will be implemented in [Solang](https://github.com/hyperledger/solang).

Additionally, Solang will also need to generate the contract metadata in ETH ABI format.

Ultimately the goal is to make existing ETH dev tooling and wallets compatible with contracts deployed on pallet `contracts`.

**Comment by athei** [comment]
Solang is deprecated and replaced by https://github.com/paritytech/revive.
