### ISSUE TITLE
CI/CD: Internal GHA marketplace

### ISSUE THREAD

**Issue by rcny** [paritytech/roadmap#19]
We should have our own GHA collection for the sakes of standardization, efficiency, collaboration and control.

---

* [Link to the milestone in the CI/CD tracker](https://github.com/paritytech/ci_cd/milestone/2)
* Estimate: _Q2 2023_

**Comment by Bullrich** [comment]
I believe that @paritytech/ci is already working on something like this. 

Could you guys confirm please?

**Comment by rcny** [comment]
Yes, please see https://github.com/paritytech-actions.

cc @sergejparity

**Comment by sergejparity** [comment]
> I believe that @paritytech/ci is already working on something like this.
> 
> Could you guys confirm please?

Yes, I do.  Here is set of issues related https://github.com/paritytech/ci_cd/issues?q=is%3Aissue+assignee%3Asergejparity+label%3Aactions+label%3Agithub
