### ISSUE TITLE
InfraEng: hosting public chain snapshots

### ISSUE THREAD

**Issue by gabreal** [paritytech/roadmap#28]
For making initial node syncs faster and reference in published polkadot-based node deployments making db snapshosts publically available would be required. Cloudflare's R2 offering seems to be worth giving a try.

ref: https://github.com/paritytech/devops/issues/913

**Comment by kogeler** [comment]
ref:
https://gitlab.parity.io/parity/infrastructure/ansible/collections/chain_operations/-/merge_requests/175
https://gitlab.parity-mgmt.parity.io/infrastructure/cloud-infra/-/merge_requests/1545
https://gitlab.parity-mgmt.parity.io/infrastructure/cloud-infra/-/merge_requests/1552

**Comment by kogeler** [comment]
ref: https://github.com/paritytech/ansible-galaxy/pull/36

**Comment by kogeler** [comment]
ref: https://github.com/paritytech/helm-charts/pull/262
