### ISSUE TITLE
Deploy Coretime on Rococo

### ISSUE THREAD

**Issue by bkchr** [paritytech/roadmap#52]
This includes:
- [ ] Upgrading the relay chain to support Coretime
- [ ] Deploy the Coretime parachain and have it registered on the relay chain
- [ ] Migration path to Coretime
- [ ] Have a simple parachain running that is using instantaneous Coretime

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/timeline-on-agile-coretime/4274/8

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-digest-17-oct-2023/4301/1

**Comment by bkchr** [comment]
A more detailed issue exists here: https://github.com/paritytech/polkadot-sdk/issues/2348
